### ISSUE TITLE
Changes Requested by Ryan

### ISSUE THREAD

**Issue by Mranfevb92** [coding-is-for-losers/seo-audit#17]
From the video he shared I made this list of all the changes Ryan mentioned. If I am missing anything please let me know: 

**1. Inconsistency with Revenue values:** 

From what I saw with Blueprint Training and 28bySamWood, it's mostly an issue with subdomains getting lost in the first parts of the process. I propose the following changes: 

- From GA, extract views and hostnames into a separate table.  Keep only ones that hold the main domain in its name (Through regex match) or maybe keep the ones that have e-commerce data? 
-  on the `domain_proc`: match with this just created table so for each site we could have more than one domain.
-  When matching with the `domain_proc` on the `ga_proc`, we should keep all subdomains where there are transactions going on. 
-  Adding Revenue to our current QC process to keep track of any inconsistency here is a last and crucial step. 

**2. Conversion Rate Mismatch**

 The formula we have in place seems to be working as it should, but have seen some cases where the conversion that appears in the Data Studio doesn't match the expected value (especially in cases with e-commerce). 

I propose adding both goal conversion (all goals) and e-commerce conversion to the report. If there is no e-commerce, we keep the measure null. That way it can be tracked consistently the minute they add e-commerce (as it happened with 28bySamWood)

This will require a change in the` ga_stats` model, and then on several models upstream that have the `blended_conversion_rate `field in them

**3. Page Type:** 

Could you share the organic pulse example you mentioned in the slack comment, please? Couldn't find it. Once I have a clear idea of what the input could look like I can implement to all existing recipes. 

Currently, page type comes `deepcrawl_stats`, can make it so we use this manual input instead of deepcrawl manual classification. 

I do have some concerns in here based on Ryan's comments: 

1. How can we make this something that can be manually overridden or changed by the end-user? Can't think of a way aside from letting them know they can adjust the classification of page type in their tracking plan and then we refresh it. 

2.  This last idea works as long as we ran manually their recipe. How can we deal with this once we migrate to the qr app? We can have a default page type classification built-in, but if they want a specific one, do we add it as a manual input or how do you think we should do it? 

**4. Create a graph for failing content**

Ryan mentioned a graph for "failing content" category in the WHAT'S NEW PAGE. Adding the graph is not an issue,  but should I create a "failing content" category or use one of the categories we already have in place in the `action_proc` model? 
             
**5. Review the "new pages" classification**

404s and 301 pages are being classified as new pages for action recommendations. I agree that the change should probably be in `actions_proc` but will notify you if I see it has to be made in another one. 

**6. New backlink extra info missing**

I understood that Ryan wants extra info on backlinks: I suppose he wants a table where you can see the # of backlinks per url? Could we add that field to the page- level detail table? Don't think that would require any change in models. Let me know what you think.

**Comment by Mranfevb92** [comment]
Setup the first set of changes on this PR #18 

Only the first commit in so far, to deal with the Revenue inconsistency and removal of the blended conversion rate. Will push new commits for the rest of the issues in the following days.

**Comment by Mranfevb92** [comment]
@codingisforlosers update on this: 

1. Tested out the new revenue calculation for Webris' sites and 28bySamWood: For webris it is working great, with a diff from the value brought from supermetrics among the 1%-3%. 

In the case of 28bySamWood the calculation is not working, but it seems to be an issue specific for this site, rather than our models. They seem to have a lot of the same landing_pages reported under different hostnames. Check the case of this landing page: it appears several different times under different hostnames, and with different values on metrics for each. The screenshot is from the `ga` table. You can imagine that when processed in ga_proc only one of these stays, and not necessarily the one with transaction values. 

![image](https://user-images.githubusercontent.com/59895543/99135799-c7d5fa00-25f0-11eb-9e09-a3e844982202.png)


2. Ecommerce /Goal Conversion

I think we should calculate these metrics directly as calculated fields in Data Studio. Check this query: 

```
SELECT 
date,
site,
sum(transactions_30d) as transactions,
sum(sessions_30d) as sessions,
sum(transaction_revenue_30d) as revenue,
avg(ecommerce_conversion_rate_30d) as ecommerce_conversion
FROM `webris-recipes.wqa.actions_data_studio`
WHERE date= '2020-10-01' and site = 'The Blueprint Training'
GROUP BY date,site
```

the e-commerce conversion we calculate in BQ doesn't match the one that we should show.

**Comment by codingisforlosers** [comment]
Thanks @Mranfevb92, some notes on these:
 
> 1. Tested out the new revenue calculation for Webris' sites and 28bySamWood: For webris it is working great, with a diff from the value brought from supermetrics among the 1%-3%.
> 
> In the case of 28bySamWood the calculation is not working, but it seems to be an issue specific for this site, rather than our models. They seem to have a lot of the same landing_pages reported under different hostnames. Check the case of this landing page: it appears several different times under different hostnames, and with different values on metrics for each. The screenshot is from the `ga` table. You can imagine that when processed in ga_proc only one of these stays, and not necessarily the one with transaction values.

I think the issue there is cross-domain tracking - so revenue is being attributed to the subdomain where the conversion happens rather than the root domain.

Only thing we can really do there, is migrate to just rolling up stats for the `landing_page_path` (rather than concatenating the URL as `hostname` + `landing_page_path`).  So URL could just be the site's root domain + `landing_page_path` from GA (of just `landing_page_path` in the event that the path contains the root domain, as is true for 28bysamwood).

This way, we may have some junk pages included in the audit, but at least sum totals would add up to the GA dashboard.
 
> 2. Ecommerce /Goal Conversion
> 
> I think we should calculate these metrics directly as calculated fields in Data Studio. Check this query:
> 
> ```
> SELECT 
> date,
> site,
> sum(transactions_30d) as transactions,
> sum(sessions_30d) as sessions,
> sum(transaction_revenue_30d) as revenue,
> avg(ecommerce_conversion_rate_30d) as ecommerce_conversion
> FROM `webris-recipes.wqa.actions_data_studio`
> WHERE date= '2020-10-01' and site = 'The Blueprint Training'
> GROUP BY date,site
> ```
> 
> the e-commerce conversion we calculate in BQ doesn't match the one that we should show.

I think there's two approaches here: in the raw line-level tables (`actions_proc` etc), we calculate the page-level conversion rate for that month, because it's used for assigning action recommendations.  

For Data Studio, however, we'll want to recalculate conversion rate as sum(transactions) / sum(sessions) (or sum(goal completions) / sum(sessions) ) as you mentioned, as an average of page-level rates won't be correct.

> **3. Page Type:**
> 

Will create a separate issue for this.  

> **4. Create a graph for failing content**
> 
> Ryan mentioned a graph for "failing content" category in the WHAT'S NEW PAGE. Adding the graph is not an issue, but should I create a "failing content" category or use one of the categories we already have in place in the `action_proc` model?

Key field there is `content_action` - actions are broken down into:

- Rising content
- Below-trend conversion rate
- Potential 301: low traffic, has external links
- Potential removal: low traffic, 0 conversions or backlinks

I think we may want to modify these definitions to be a bit easier to understand - right now they're somewhat convoluted, and keyed off of click-through rate + conversion rate changes:

```
WHEN http_status_code = 200 AND sessions_mom_pct > total_organic_sessions_mom_pct and ctr_mom_pct > total_ctr_mom_pct THEN 'Rising content'
	WHEN http_status_code = 200 AND transactions_30d > 0 and sessions_30d > med_sessions_30d and ecommerce_conversion_rate_mom_pct < total_organic_ecommerce_conversion_rate_mom_pct THEN 'Below-trend conversion rate'

```

Maybe we could simplify the logic by making 'rising content' + 'falling content' simple calculations of the amount of relative traffic they gained / lost over the month compared to the previous month.  

Maybe we roll in some of the Organic Pulse logic here?  Ryan and I have been discussing whether we should fold these into one Recipe, since the underlying data is the same.  Basically the OP could be the daily report version of the WQA. 

> **5. Review the "new pages" classification**
> 
> 404s and 301 pages are being classified as new pages for action recommendations. I agree that the change should probably be in `actions_proc` but will notify you if I see it has to be made in another one.

The field to review here is `new_content_flag` in `actions_hierarchy`:

```

CASE WHEN sessions_30d = sessions_ttm AND sessions_30d > 0 THEN 1
	ELSE 0 END as new_content_flag,

```

We can add a `WHEN http_status_code = 200` condition here to solve the issue.  We may want a more nuanced way of picking up if it's a new page, but I think `sessions_30d` equaling sessions from the last year is a decent proxy.


> **6. New backlink extra info missing**
> 
> I understood that Ryan wants extra info on backlinks: I suppose he wants a table where you can see the # of backlinks per url? Could we add that field to the page- level detail table? Don't think that would require any change in models. Let me know what you think.

Yeah exactly - think it'd be helpful to just see a page-level view of which pages are gaining / losing backlinks (with a period-over-period comparison).

**Comment by Mranfevb92** [comment]
I've added a new commit to the PR #18 yesterday. Included changes based on your comments about revenue, and the changes for the failing content + new page classification. 

Was thinking that when I first set up this issue, I forgot to include the schema_checks we discussed on [slack](https://webrisagency.slack.com/archives/DNQTRNHR7/p1605202206002900) based on Melissa's request. There is indeed a breadcrumb field in deepcrawl. Should we shift the logic to this new field?

**Comment by codingisforlosers** [comment]
Re the breadcrumb field, yes we could switch to using that, but believe we’ll have to modify the integration to pick it up as a column right?

If you can look up the column field from the Deepcrawl API docs and add it to the App trello board as a ticket, I’ll have Gonzalo make that change.

—
David Krevitt
Commissioner, CodingIsForLosers

**Comment by Mranfevb92** [comment]
Update the pr #18 based on your latest comments: 

* Adjusted the `ga_proc` so the join is through the ga account/ gsc account instead of by hostname.

* returned the `domain_proc` to its original version + an adjustment to calculate the` lv `field using the analytics and search console account on the partition.

*Adjustments to the s`earch_console_url_proc` and` search_console_keyword_proc` so they match through account with the `domain_proc`

*created `action_trajectory` and modified `content_action` accordingly.

* added `action_trajectory` to all subsequent models after actions_proc

**Comment by codingisforlosers** [comment]
Thanks - left one comment on the PR, but otherwise looks good.

In terms of rolling this out, want to make a checklist (can be in a separate issue) for where we'd like to incorporate `content_trajectory` in DS reporting?  

Doesn't need to be anything major - just making sure breakouts of it are visible in the same way that it was previously visible in `content_action` views.

**Comment by Mranfevb92** [comment]
I pushed the latest changes based on your comments and approved the PR. I am working on the checklist for changes on the DS -- We need to include content_trajectory, but also change other stuff based on the changes. Will share it in a little while. 

From this issue, we are still missing one item. Will delete the issue once we complete it. 

- [ ] _Changing the way we track breadcrumb schema:_ Will work on this once Gonzalo adds the extra field in the d[eepcrawl integration ](https://trello.com/c/HWUCBNGW/315-extra-fields-for-deepcrawl-integration-breadcrumbs-custom-extractions)

**Comment by Mranfevb92** [comment]
@codingisforlosers fyi, here is the issue with the checklist for the changes in the DS report: #20

**Comment by Mranfevb92** [comment]
@codingisforlosers Here are the latest changes request made by Ryan/Cesar.: 

- [ ] Update metas to include main or best keyword: I suppose that he means the search for the main/best keyword within the URL or page title. If I understand this correctly, it would require a big change in the logic of the keywords models. The Predator Nutrition workbook is 

- [ ] Potential 301: Low Traffic has External Links: Include pageviews into the logic of determining this action. This one is doable, but I do believe that page views and sessions are correlated. What we should consider is having this action recommend only to "blog posts" as Cesar suggested. 

- [ ] Change the Rolling Monthly History Graph: Include revenue vs conversion rate. Right now it shows e-commerce conversion rate, goal conversion rate, and sessions. 

- [ ] Filter out pages with no "Found at URL"/ "Found at Sitemap" info. We'll keep only those that have found_at info on them (GA/GSC)

- [ ] Map to the correct found_at_sitemap and found_at_url fields in cases with self-redirects and query string versions of its URL (like discussed on [slack](https://webrisagency.slack.com/archives/DNQTRNHR7/p1606934084003100) )

I'll work on an update to the deal with the last two today. We can discuss further the other changes proposed

**Comment by Mranfevb92** [comment]
Moved the new requests in the last comment to individual issues, so we can discuss each in more detail. Will close this issue.
