### ISSUE TITLE
Manual page type classification

### ISSUE THREAD

**Issue by codingisforlosers** [coding-is-for-losers/seo-audit#19]
There are a two main ways to specify page type classifications: 

- by matching a regex pattern in the URL path (URLs containing /blog/ = 'blog posts')
- by specific elements on a given page to search for in the crawl via custom extractions (pages containing a form with id="blog-form" = 'blog posts').

The second method (regex custom extractions) is more accurate, since URL structure on a site might not be indicative of site sections / page types.

Also, we're already using subfolder as a proxy for page type (when we're not apply to find any other mapping), so I don't think that building a manual workflow around subfolder regex would be a good move.

Inflow also just asked this week to classify page types via custom extractions, let's explore what we'd need to get that done scalably - FYI I don't think the Organic Pulse method is relevant here if we're using custom extractions:

1) The user would have to provide us a list of custom extractions that correspond to each page type (believe Deepcrawl can support up to 20 custom extractions and therefore page types).  

We can set this up now via the Tracking Plan, and later on could modify the QR integration to support this (as of now we set up default custom extractions for them, so we already have functionality to interact with custom extractions).

2) We'd have to create custom extractions with vanilla / non-specific names (ie `custom_extraction_1`, `custom_extraction_2`, etc), so that the BigQuery schema could remain the same for every site, even if the underlying page types implied by each mapping is different.

3) To map the vanilla column names (`custom_extraction_1` back to actual page types `blog post`, we'd need to model the hierarchy of extraction #s to page type names (this can be done by reading in the Tracking Plan settings in the manual version, but in QR we can add  `custom_extraction_1_page_type` etc metadata columns to help this processing).

4) We'd then apply a `page_type` hierarchy in the deepcrawl models, basically a big CASE statement that iterates through all of the page type hierarchies present.

For this final step, we could use some of the Organic Pulse logic (see [keyword_mappings_proc](https://github.com/coding-is-for-losers/qr-organic-pulse/blob/master/models/admin/keyword_mappings_proc.sql) which builds the mapping table, and [gsc_proc](https://github.com/coding-is-for-losers/qr-organic-pulse/blob/master/models/base/search-console/gsc_proc.sql) where they're applied).

LMK what you think of this approach!

**Comment by Mranfevb92** [comment]
@codingisforlosers Hey David, been looking into this and have a couple of comments: 

1.  In their last email, Inflow requested separate inputs for categories/subcategories. We might need to modify the page type classification tab. I propose the columns below for this new classification: 

  > Site Name
  > Custom Extraction Regex
  > Page Level (To determine if category or subcategory)
  >Category-subcategory description
  > Hierarchy -- this one we may need to re-do the formula, as I assume there would be a hierarchy for both categories and 
   subcategories 

2. Checking our setup of deepcrawl, we already use custom_extractions. Around 11 of the 30 available are in use. We extract stuff like google_maps, schema_type, form_submit, infinite_scroll, among other stuff from the current setup. You can check [WEBRIS example](https://app.deepcrawl.com/accounts/26592/projects/331170/crawls/3240202/edit?step=4), but all sites must have the same setup. 

This is not a huge issue, as we can still set page classification as custom extractions, and keep the vanilla naming format (custom_extraction_1, custom_extraction_2, etc..), but it does limit the potential number of extractions for page categories, even more so if we decide to split categories and subcategories. Let me know how you think we should handle this. 

Aside from that, I am ready to begin writing the models using an example from WEBRIS. Could you help me set up a mock page type classification for webris or the blueprint so I can test it up? I already added the tab to the [WEBRIS tracking plan](https://docs.google.com/spreadsheets/d/1OcAbr8-yJ9Bu0bJeaYb6H890bPy85n18XS3cbUbkFvY/edit#gid=642809197)

**Comment by codingisforlosers** [comment]
Thanks Andres - we may remove some of those existing 11 extractions as part of this, but we’ll see.  I’d say 10-15 slots should be plenty.

Pinged Cesar on Slack to start mapping these out for Webris, and once we have a concrete example we can get to implementing.

One thing we may need here integration-wise from the app’s Deepcrawl integration, is automatically pulling all custom extraction columns that are available (probably need dummy columns 1-30 in the schema to start with), and keeping the col names vanilla (custom_extraction_1) rather than by name.

Want to add that to the DC ticket for the breadcrumb addition?

—
David Krevitt
Commissioner, CodingIsForLosers

**Comment by Mranfevb92** [comment]
I'll add a comment to the trello card for breadcrumb + custom_extractions. 

Cesar just responded on slack. He mentions the possibility of manually overriding the page type after the process. If we were to keep the WQA sheet it would be easy to just add a "manual-input" column for them to override any misclassification, but can't think of a way to properly achieve the same thing in DS, especially once we move towards the qr setup. Should we give this a thought or just tell them that it's not possible?

**Comment by codingisforlosers** [comment]
@Mranfevb92 thinking about the approach on #27 with regards to page types.  

It seems like a good use case for bulk updates (on a `Bulk Page Type Updates` tab), likely by setting a `first_subfolder` or `second_subfolder` as belonging to a specific page type.  

Thoughts?  I'd be concerned that regex (rather than exact match) rules would result in confusion for people, but I feel like some type of bulk setting would be helpful.

For example, if all blog posts live in /random-folder/, you wouldn't want to require someone to update the page type everytime a new URL is added to that subfolder.

**Comment by Mranfevb92** [comment]
Agree, regex can be difficult to understand. And yes, a good use for bulk updates would be to modify page types in bulk. 

Should we give them both options? Evaluate and change page types in bulk as you proposed, and then also update on a per URL basis?

**Comment by codingisforlosers** [comment]
Yep we can provide both, will see if we can mock a similar setup for bulk updates on both page types + action reviews

—
David Krevitt
Commissioner, CodingIsForLosers

**Comment by codingisforlosers** [comment]
Closing this for now, updated workbook here:
https://docs.google.com/spreadsheets/d/1fIVEYN7mlj2fyeq5ySmz-zsuiquoylLYX0iW4QoZ0LU/edit#gid=1599954048

We'll circle back to this when we add regex page type classification, but for now no user (neither Cesar nor Inflow who asked for it) has followed up with actual regex settings to configure
