### ISSUE TITLE
WQA Data Studio Report Update

### ISSUE THREAD

**Issue by Mranfevb92** [coding-is-for-losers/seo-audit#20]
Here is the list of changes that I propose for the WQA report. Please add the ones that are missing or correct if you think is not adequate. I'll make the changes on the main [WQA template](https://datastudio.google.com/u/0/reporting/1SXiDGvfOZT0GWgD3OFvE0ax5kdjY3VwL/page/hxsFB), before implementing in each individual WQA we have in place. 

Page 1: 

- [x] Add scorecards for goal-conversion rate and E-commerce Conversion rate

- [x] Create calculated fields for both goal-conversion rate and e-commerce conversion rate

- [x] Modify Rolling Monthly History: Include the goal conversion rate and e-commerce conversion

Page 2: What's new this month 

- [x] Create a falling vs rising pages table
- [x] Create a falling content (as opposed to rising content) table 
- [x] Page Level detail on Backlinks table

Page 3: What's new (All-Time) 

- [x] Create falling vs rising pages table
- [x] Page-level detail on backlinks table

Page 6: Actions (Exports):

- [x] Add a Content_trajectory filter in the Export On-Page / Off Page Actions table
- [x] Add Content trajectory as a dimension in the table

**Comment by codingisforlosers** [comment]
@Mranfevb92 these look great, thanks - feel free to go ahead and implement as part of the monthend process

**Comment by Mranfevb92** [comment]
Quick update: added this PR #21 to add a field that was missing for the changes in page 3: the content_trajectory_first. Given that its a small change, I approved it.

**Comment by Mranfevb92** [comment]
Made the changes. The ones I haven't marked above are for the following reasons: 

* Page Level detail on backlinks Table (page 1): I did add the backlink count to the table, didn't create an extra table for this. Let me know if you think we should add an extra table for backlinks exclusively at the bottom. 

* Create rising/falling table (page 3): Didn't add this one as the first_value option of content_trajectory is always blank (there is no previous month to compare it to in the calculation). I could change the formula so it uses the second to last month if you think adding this table here would be best

Once these two comments above are sorted, I'll implement the changes in all individual reports

**Comment by codingisforlosers** [comment]
Looks good!  And yes you're good on those two comments, we can leave out the 'all time' rising content for now.  

Let's just double-check that the descriptions of rising / falling content (looking at page 2 but might also be elsewhere) are updated with these new definitions.

![image](https://user-images.githubusercontent.com/16282439/100471401-d2d46400-309f-11eb-8170-9a2c29211725.png)

We'll also want to update these definitions in the the SOP doc / QR intercom docs for the recipe.

**Comment by Mranfevb92** [comment]
Changed the definitions of rising/falling content and the actions content recommendations on this [WQA SOP](https://app.intercom.com/a/apps/ry65u35x/articles/articles/4256828/show) on intercom. Do we have another doc that covers the WQA?

**Comment by codingisforlosers** [comment]
Thanks!  There’s the original google docs SOP as well

—
David Krevitt
Commissioner, CodingIsForLosers
