### ISSUE TITLE
Potential 301: Low Traffic Action - Calculation Change

### ISSUE THREAD

**Issue by Mranfevb92** [coding-is-for-losers/seo-audit#26]
Requested in [this](https://webrisagency.slack.com/archives/C01C2GR0VDM/p1606759077005700) comment, Cesar recommends adding pageviews to the logic of determining the action **Potential 301: Low Traffic Action**

Additionally, suggests this action be assigned only to Blog Posts. Based on this last recommendation, dealing with this after we make the change to the #19 issue.

**Comment by codingisforlosers** [comment]
Updated qr-wqa to only apply these content actions (301 / removal) to page_type = 'blog'
